"""Validate the human-edited UI table and deterministic, offline runtime assets.

Default is read-only release validation. --generate updates generated assets only.
No third-party packages, script conversion, network or locale fallback.
"""
from __future__ import annotations

import argparse
import csv
import io
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UI = ROOT / "desktop" / "ui"
LOCALES = ("zh-HK", "zh-TW", "zh-CN", "en")
COLUMNS = ("key", "screen", "note", *LOCALES)
KEY = re.compile(r"[a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)+")
PLACEHOLDER = re.compile(r"\{([a-z][a-z0-9_]*)\}")


class TranslationError(ValueError):
    pass


def placeholders(value: str) -> set[str]:
    if "{" in PLACEHOLDER.sub("", value) or "}" in PLACEHOLDER.sub("", value):
        raise TranslationError(f"Malformed placeholder: {value!r}")
    return set(PLACEHOLDER.findall(value))


def parse_table(text: str) -> dict[str, dict[str, str]]:
    reader = csv.reader(io.StringIO(text, newline=""), strict=True)
    messages: dict[str, dict[str, str]] = {locale: {} for locale in LOCALES}
    try:
        if tuple(next(reader, [])) != COLUMNS:
            raise TranslationError(f"CSV header must be {','.join(COLUMNS)}")
        for row in reader:
            if len(row) != len(COLUMNS):
                raise TranslationError(f"Row {reader.line_num}: expected {len(COLUMNS)} columns")
            key, screen, note, *values = row
            if not KEY.fullmatch(key) or key in messages[LOCALES[0]]:
                raise TranslationError(f"Row {reader.line_num}: invalid or duplicate key {key!r}")
            if not screen.strip() or not note.strip():
                raise TranslationError(f"{key}: screen and collaboration note are required")
            expected = placeholders(values[-1])
            for locale, value in zip(LOCALES, values):
                if not value.strip():
                    raise TranslationError(f"{locale}: missing key {key}")
                if placeholders(value) != expected:
                    raise TranslationError(f"{locale}: placeholder mismatch for {key}")
                if any(0x1F1E6 <= ord(char) <= 0x1F1FF for char in value):
                    raise TranslationError(f"{key}: flags are not UI locale labels")
                messages[locale][key] = value
    except csv.Error as error:
        raise TranslationError(f"Malformed CSV at row {reader.line_num}: {error}") from error
    if not messages[LOCALES[0]]:
        raise TranslationError("Translation table is empty")
    return messages


def references(ui: Path) -> set[str]:
    refs: set[str] = set()
    for path in sorted(ui.glob("*.html")) + sorted(ui.glob("*.js")):
        source = path.read_text(encoding="utf-8")
        refs.update(re.findall(r'data-i18n(?:-placeholder|-label)?=[\"\']([^\"\']+)', source))
        # Dynamic maps register literal keys via key(...); no inferred English keys.
        refs.update(re.findall(r"\b(?:t|key)\(['\"]([^'\"]+)['\"]", source))
    return refs


def artifacts(messages: dict[str, dict[str, str]]) -> dict[str, str]:
    result = {
        f"locales/{locale}.json": json.dumps(messages[locale], ensure_ascii=False, sort_keys=True, indent=2) + "\n"
        for locale in LOCALES
    }
    # Classic-script bundle avoids network fetch/module-loader requirements in Tauri.
    result["locales.js"] = (
        "// Generated by scripts/check_ui_translations.py; edit ui-strings.csv instead.\n"
        "globalThis.HanContextMessages = "
        + json.dumps(messages, ensure_ascii=False, sort_keys=True, indent=2) + ";\n"
    )
    return result


def validate(ui: Path = UI, generate: bool = False) -> list[str]:
    messages = parse_table((ui / "i18n/ui-strings.csv").read_text(encoding="utf-8-sig"))
    keys = set(messages[LOCALES[0]])
    unknown = references(ui) - keys
    if unknown:
        raise TranslationError(f"Code references unknown keys: {', '.join(sorted(unknown))}")
    expected = artifacts(messages)
    target = ui / "i18n"
    if generate:
        for name, content in expected.items():
            path = target / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    drift = [name for name, content in expected.items()
             if not (target / name).is_file() or (target / name).read_text(encoding="utf-8") != content]
    extras = sorted(p.name for p in (target / "locales").glob("*.json") if p.name not in {f"{loc}.json" for loc in LOCALES})
    if drift or extras:
        raise TranslationError(f"Generated resources differ: {drift}; unknown locale resources: {extras}. Run --generate.")
    return [f"{locale}: {len(messages[locale])}/{len(keys)} complete; missing keys: none" for locale in LOCALES]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generate", action="store_true", help="Regenerate static resources after editing CSV")
    args = parser.parse_args()
    try:
        for line in validate(generate=args.generate):
            print(line)
    except (OSError, UnicodeError, TranslationError) as error:
        print(f"UI translations FAIL: {error}", file=sys.stderr)
        return 1
    print("UI translations PASS (all locales, placeholders, references, generated resources)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
